<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2</TargetFramework>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>NU1605</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="3.4.0" />
    <PackageReference Include="ugcs-dotnet-sdk" Version="5.17.0" />
  </ItemGroup>

</Project>